
import React, { useState, useEffect, useRef } from 'react';
import { CityLocation, CityData, SupabaseConfig } from './types';
import { fetchCityData } from './services/openRouterService';
import { saveToSupabase, checkIfCityExists, fetchAllExistingCities } from './services/supabaseService';

const HARDCODED_URL = 'https://rdxgozeijdwghbbwivdy.supabase.co';
const HARDCODED_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkeGdvemVpamR3Z2hiYndpdmR5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODIyOTEzMSwiZXhwIjoyMDgzODA1MTMxfQ.IvchfZ829eEclTgI8c4BfQoyNfvvcWnd9Kxq09U-Y_o';
const DEFAULT_TABLE = 'neighborhoods';
const DEFAULT_CONCURRENCY = 10;

const SQL_TEMPLATE = `-- 1. Run this to create or update the table structure
CREATE TABLE IF NOT EXISTS neighborhoods (
    id bigint generated by default as identity primary key,
    city text not null,
    state text not null,
    neighborhoods text[],
    famous_buildings text[],
    description text,
    sources jsonb,
    created_at timestamptz default now(),
    CONSTRAINT city_state_unique UNIQUE (city, state)
);`;

const App: React.FC = () => {
  const [inputText, setInputText] = useState('');
  const [recentLogs, setRecentLogs] = useState<CityData[]>([]);
  const citiesRef = useRef<CityData[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState({ current: 0, total: 0, skipped: 0, errors: 0 });
  const [showSettings, setShowSettings] = useState(false);
  const [concurrency, setConcurrency] = useState(DEFAULT_CONCURRENCY);
  const [sbConfig, setSbConfig] = useState<SupabaseConfig>({
    url: HARDCODED_URL,
    key: HARDCODED_KEY,
    tableName: DEFAULT_TABLE
  });
  const [copied, setCopied] = useState(false);

  const processingRef = useRef(false);

  useEffect(() => {
    const saved = localStorage.getItem('supabase_config');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setSbConfig({
          url: parsed.url || HARDCODED_URL,
          key: parsed.key || HARDCODED_KEY,
          tableName: parsed.tableName || DEFAULT_TABLE
        });
      } catch (e) { }
    }

    const cachedInput = localStorage.getItem('cached_input');
    if (cachedInput) setInputText(cachedInput);
  }, []);

  const saveSettings = () => {
    localStorage.setItem('supabase_config', JSON.stringify(sbConfig));
    setShowSettings(false);
  };

  const copySql = () => {
    navigator.clipboard.writeText(SQL_TEMPLATE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const parseInput = (text: string): CityLocation[] => {
    return text
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.includes(','))
      .map(line => {
        const parts = line.split(',');
        const city = parts[0].trim();
        const state = parts.slice(1).join(',').trim();
        return { city, state };
      });
  };

  const exportToCSV = () => {
    const headers = ["City", "State", "Status", "Neighborhoods", "Landmarks"];
    const rows = citiesRef.current.map(c => [
      `"${c.city}"`,
      `"${c.state}"`,
      `"${c.status}"`,
      `"${(c.neighborhoods || []).join("; ")}"`,
      `"${(c.famous_buildings || []).join("; ")}"`
    ]);
    const csvContent = [headers, ...rows].map(e => e.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `city_sync_report_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
  };

  const getCachedCompleted = () => {
    try {
      const item = localStorage.getItem('completed_cities_map');
      return new Set(item ? JSON.parse(item) : []);
    } catch { return new Set(); }
  };

  const addToCache = (city: string, state: string) => {
    const current = getCachedCompleted();
    current.add(`${city}|${state}`);
    localStorage.setItem('completed_cities_map', JSON.stringify(Array.from(current)));
  };

  const syncFromDb = async () => {
    if (!confirm("⚠️ This will REPLACE your local cache with the exact list from the Database.\nAny 'ghost' completed items (not really in DB) will be removed so they can be re-processed.\n\nContinue?")) return;

    setIsProcessing(true);
    try {
      const existing = await fetchAllExistingCities();

      // Create a FRESH set from DB data only (Mirroring)
      const freshCache = new Set<string>();
      existing.forEach(rec => {
        freshCache.add(`${rec.city}|${rec.state}`);
      });

      localStorage.setItem('completed_cities_map', JSON.stringify(Array.from(freshCache)));
      alert(`Sync Complete! Cache is now identical to DB.\n\nTotal in DB: ${freshCache.size}\nLocal Cache Updated.\n\nNon-existent items will now be re-processed.`);
    } catch (e) {
      alert("Error syncing from DB");
    } finally {
      setIsProcessing(false);
    }
  };

  const processCity = async (loc: CityLocation, index: number) => {
    if (!processingRef.current) return;

    // Check local cache first (FAST RESUME)
    const localCache = getCachedCompleted();
    if (localCache.has(`${loc.city}|${loc.state}`)) {
      // Update data in Ref (silent update)
      if (citiesRef.current[index]) {
        citiesRef.current[index].status = 'completed';
        citiesRef.current[index].error = "Skipped (Locally Cached)";
      }
      setProgress(p => ({ ...p, current: p.current + 1, skipped: p.skipped + 1 }));
      return;
    }

    try {
      // 1. Mark as Processing (Visual Log)
      setRecentLogs(prev => [{ ...loc, status: 'processing', neighborhoods: [], famous_buildings: [] } as CityData, ...prev].slice(0, 50));

      const exists = await checkIfCityExists(loc.city, loc.state);

      if (exists) {
        addToCache(loc.city, loc.state);
        // Update Ref
        if (citiesRef.current[index]) {
          citiesRef.current[index].status = 'completed';
          citiesRef.current[index].error = "Skipped (Exists)";
        }

        // Log Update
        setRecentLogs(prev => [{ ...citiesRef.current[index] }, ...prev].slice(0, 50));
        setProgress(p => ({ ...p, current: p.current + 1, skipped: p.skipped + 1 }));
        return;
      }

      const result = await fetchCityData(loc);

      const completedData: CityData = {
        ...loc,
        neighborhoods: result.neighborhoods || [],
        famous_buildings: result.famous_buildings || [],
        description: result.description || "",
        sources: result.sources || [],
        status: 'completed'
      };

      // Update Ref
      citiesRef.current[index] = completedData;

      // Update Log
      setRecentLogs(prev => [completedData, ...prev].slice(0, 50));

      await saveToSupabase(completedData);
      addToCache(loc.city, loc.state);
      setProgress(p => ({ ...p, current: p.current + 1 }));

    } catch (error: any) {
      console.error(`Error processing ${loc.city}:`, error);

      if (citiesRef.current[index]) {
        citiesRef.current[index].status = 'failed';
        citiesRef.current[index].error = error.message || "Error";
      }

      setRecentLogs(prev => [{ ...citiesRef.current[index] }, ...prev].slice(0, 50));
      setProgress(p => ({ ...p, current: p.current + 1, errors: p.errors + 1 }));
    }
  };

  const startProcessing = async () => {
    const locations = parseInput(inputText);
    if (locations.length === 0) {
      alert("Please enter a valid list of 'City, State' pairs.");
      return;
    }

    setIsProcessing(true);
    processingRef.current = true;
    setProgress({ current: 0, total: locations.length, skipped: 0, errors: 0 });

    const initialList: CityData[] = locations.map(loc => ({
      city: loc.city,
      state: loc.state,
      neighborhoods: [],
      famous_buildings: [],
      description: '',
      sources: [],
      status: 'pending'
    }));
    citiesRef.current = initialList;
    setRecentLogs([]);

    const queue = [...locations.keys()];
    const workers = [];

    const worker = async () => {
      while (queue.length > 0 && processingRef.current) {
        const index = queue.shift();
        if (index !== undefined) {
          await processCity(locations[index], index);
        }
      }
    };

    for (let w = 0; w < Math.min(concurrency, locations.length); w++) {
      workers.push(worker());
    }

    await Promise.all(workers);

    setIsProcessing(false);
    processingRef.current = false;
  };

  const stopProcessing = () => {
    processingRef.current = false;
    setIsProcessing(false);
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <header className="bg-white border-b sticky top-0 z-20 px-6 py-4 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="bg-indigo-600 w-10 h-10 rounded-xl flex items-center justify-center text-white shadow-lg shadow-indigo-200">
            <i className="fas fa-microchip text-xl"></i>
          </div>
          <div>
            <h1 className="text-xl font-black text-slate-800 tracking-tight uppercase">Bulk GeoSync Engine</h1>
            <p className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Powered by Gemini-3 Flash & Supabase</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {progress.total > 0 && (
            <button
              onClick={exportToCSV}
              className="px-3 py-2 text-[11px] font-black uppercase tracking-widest text-slate-600 hover:text-indigo-600 transition-colors flex items-center gap-2"
            >
              <i className="fas fa-file-export"></i> Export CSV
            </button>
          )}

          {isProcessing ? (
            <button
              onClick={stopProcessing}
              className="px-6 py-2 bg-red-500 text-white rounded-xl font-bold hover:bg-red-600 transition-all flex items-center gap-2 shadow-lg shadow-red-200"
            >
              <i className="fas fa-stop text-sm"></i> PAUSE ENGINE
            </button>
          ) : (
            <button
              onClick={startProcessing}
              disabled={!inputText.trim()}
              className="px-8 py-2 bg-indigo-600 text-white rounded-xl font-black uppercase tracking-widest hover:bg-indigo-700 disabled:opacity-30 disabled:grayscale transition-all flex items-center gap-2 shadow-lg shadow-indigo-200"
            >
              <i className="fas fa-play text-sm"></i> START BATCH
            </button>
          )}

          <div className="h-6 w-[1px] bg-slate-200 mx-2"></div>

          <button
            onClick={syncFromDb}
            className="px-3 py-2 text-[11px] font-bold uppercase tracking-widest text-slate-500 hover:text-indigo-600 border border-slate-200 rounded-xl bg-white transition-colors"
            title="Fetch all completed cities from DB to skip them"
          >
            <i className="fas fa-sync-alt mr-1"></i> Sync DB
          </button>

          <button
            onClick={() => setShowSettings(true)}
            className="p-2.5 text-slate-500 hover:text-indigo-600 bg-white border border-slate-200 rounded-xl"
          >
            <i className="fas fa-cog"></i>
          </button>
        </div>
      </header>

      <main className="flex-1 px-6 py-6">
        <div className="max-w-7xl mx-auto">
          <textarea
            value={inputText}
            onChange={(e) => {
              setInputText(e.target.value);
              localStorage.setItem('cached_input', e.target.value);
            }}
            placeholder="Enter cities (one per line):&#10;New York, NY&#10;Los Angeles, CA&#10;Chicago, IL"
            className="w-full h-48 p-4 border border-slate-300 rounded-xl font-mono text-sm resize-none focus:outline-none focus:ring-2 focus:ring-indigo-500"
          />

          {progress.total > 0 && (
            <div className="mt-4 p-6 bg-white rounded-xl border border-slate-200">
              <div className="grid grid-cols-4 gap-4 mb-4 text-center">
                <div className="p-3 bg-slate-50 rounded-lg">
                  <div className="text-2xl font-black text-slate-800">{progress.total}</div>
                  <div className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Total Cities</div>
                </div>
                <div className="p-3 bg-green-50 rounded-lg">
                  <div className="text-2xl font-black text-green-600">{progress.current - progress.errors}</div>
                  <div className="text-[10px] font-bold text-green-700/60 uppercase tracking-widest">Completed</div>
                </div>
                <div className="p-3 bg-indigo-50 rounded-lg">
                  <div className="text-2xl font-black text-indigo-600">{progress.total - progress.current}</div>
                  <div className="text-[10px] font-bold text-indigo-700/60 uppercase tracking-widest">Pending</div>
                </div>
                <div className="p-3 bg-red-50 rounded-lg">
                  <div className="text-2xl font-black text-red-600">{progress.errors}</div>
                  <div className="text-[10px] font-bold text-red-700/60 uppercase tracking-widest">Failed</div>
                </div>
              </div>

              <div className="flex justify-between text-xs mb-2">
                <span className="font-bold text-slate-600">Processing Progress</span>
                <span className="text-slate-500">{Math.round((progress.current / progress.total) * 100)}%</span>
              </div>
              <div className="w-full bg-slate-200 rounded-full h-3 overflow-hidden">
                <div
                  className="bg-indigo-600 h-3 transition-all duration-300 ease-out"
                  style={{ width: `${(progress.current / progress.total) * 100}%` }}
                />
              </div>
              <div className="mt-2 text-right">
                <button
                  onClick={() => {
                    if (confirm('Are you sure? This will verify all cities against the database again.')) {
                      localStorage.removeItem('completed_cities_map');
                      alert('Cache cleared. You can restart the batch.');
                    }
                  }}
                  className="text-[10px] text-slate-400 hover:text-red-500 underline"
                >
                  Clear Local Cache (Force Re-check)
                </button>
              </div>
            </div>
          )}

          {recentLogs.length > 0 && (
            <div className="mt-6 space-y-2">
              <div className="flex items-center gap-2 mb-2 px-2">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                <h3 className="text-sm font-bold text-slate-500 uppercase tracking-widest">Live Activity Log (Last 50)</h3>
              </div>

              {recentLogs.map((city, idx) => (
                <div
                  key={`${city.city}-${idx}`}
                  className="bg-white rounded-xl border border-slate-200 overflow-hidden"
                >
                  <div className="p-4 flex justify-between items-center cursor-pointer hover:bg-slate-50 transition-colors"
                    onClick={() => {
                      const el = document.getElementById(`details-${idx}`);
                      if (el) el.classList.toggle('hidden');
                    }}
                  >
                    <div>
                      <div className="font-bold text-slate-800 flex items-center gap-2">
                        {city.city}, {city.state}
                        {city.status === 'completed' && (
                          <span className="text-[10px] font-normal text-slate-500 bg-slate-100 px-2 py-0.5 rounded-full">
                            {city.neighborhoods?.length || 0} items found
                          </span>
                        )}
                      </div>
                      {city.error && <div className="text-xs text-red-500 mt-1">{city.error}</div>}
                    </div>
                    <div className="flex items-center gap-3">
                      <div className={`px-3 py-1 rounded-full text-xs font-bold ${city.status === 'completed' ? 'bg-green-100 text-green-700' :
                        city.status === 'processing' ? 'bg-blue-100 text-blue-700 animate-pulse' :
                          city.status === 'failed' ? 'bg-red-100 text-red-700' :
                            'bg-slate-100 text-slate-700'
                        }`}>
                        {city.status === 'processing' ? 'Processing...' : city.status}
                      </div>
                    </div>
                  </div>

                  {/* Details View */}
                  <div id={`details-${idx}`} className="hidden border-t border-slate-100 bg-slate-50 p-4 text-sm">
                    {city.status === 'completed' ? (
                      <div className="grid md:grid-cols-2 gap-4">
                        <div>
                          <h4 className="font-bold text-indigo-600 mb-2 uppercase text-[10px] tracking-widest">Neighborhoods / Areas</h4>
                          {city.neighborhoods && city.neighborhoods.length > 0 ? (
                            <ul className="list-disc list-inside text-slate-600 space-y-1 max-h-40 overflow-y-auto">
                              {city.neighborhoods.map((n, i) => <li key={i}>{n}</li>)}
                            </ul>
                          ) : (
                            <p className="text-slate-400 italic">No specific neighborhoods found.</p>
                          )}
                        </div>
                        <div>
                          <h4 className="font-bold text-indigo-600 mb-2 uppercase text-[10px] tracking-widest">Landmarks / Buildings</h4>
                          {city.famous_buildings && city.famous_buildings.length > 0 ? (
                            <ul className="list-disc list-inside text-slate-600 space-y-1 max-h-40 overflow-y-auto">
                              {city.famous_buildings.map((b, i) => <li key={i}>{b}</li>)}
                            </ul>
                          ) : (
                            <p className="text-slate-400 italic">No landmarks found.</p>
                          )}
                        </div>
                        <div className="md:col-span-2 mt-2">
                          <h4 className="font-bold text-indigo-600 mb-1 uppercase text-[10px] tracking-widest">Overview</h4>
                          <p className="text-slate-600">{city.description}</p>
                          {city.sources && city.sources.length > 0 && (
                            <div className="mt-2 text-xs text-slate-400">
                              <span className="font-bold">Source:</span> {city.sources[0].title}
                            </div>
                          )}
                        </div>
                      </div>
                    ) : (
                      <p className="text-slate-400 italic text-center py-2">Details will appear here after processing.</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>

      {showSettings && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl p-6 max-w-2xl w-full">
            <h2 className="text-xl font-bold mb-4">Settings</h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-bold mb-1">Supabase URL</label>
                <input
                  type="text"
                  value={sbConfig.url}
                  onChange={(e) => setSbConfig({ ...sbConfig, url: e.target.value })}
                  className="w-full p-2 border rounded"
                />
              </div>

              <div>
                <label className="block text-sm font-bold mb-1">Supabase Service Role Key</label>
                <input
                  type="password"
                  value={sbConfig.key}
                  onChange={(e) => setSbConfig({ ...sbConfig, key: e.target.value })}
                  className="w-full p-2 border rounded"
                />
              </div>

              <div>
                <label className="block text-sm font-bold mb-1">Table Name</label>
                <input
                  type="text"
                  value={sbConfig.tableName}
                  onChange={(e) => setSbConfig({ ...sbConfig, tableName: e.target.value })}
                  className="w-full p-2 border rounded"
                />
              </div>

              <div>
                <label className="block text-sm font-bold mb-1">Concurrency ({concurrency})</label>
                <input
                  type="range"
                  min="1"
                  max="20"
                  value={concurrency}
                  onChange={(e) => setConcurrency(Number(e.target.value))}
                  className="w-full"
                />
              </div>

              <div className="border-t pt-4">
                <div className="flex justify-between items-center mb-2">
                  <label className="block text-sm font-bold">SQL Setup</label>
                  <button
                    onClick={copySql}
                    className="px-3 py-1 text-xs bg-indigo-600 text-white rounded hover:bg-indigo-700"
                  >
                    {copied ? '✓ Copied!' : 'Copy SQL'}
                  </button>
                </div>
                <pre className="bg-slate-50 p-3 rounded text-xs overflow-auto max-h-40">
                  {SQL_TEMPLATE}
                </pre>
              </div>
            </div>

            <div className="flex gap-2 mt-6">
              <button
                onClick={saveSettings}
                className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700"
              >
                Save
              </button>
              <button
                onClick={() => setShowSettings(false)}
                className="flex-1 px-4 py-2 bg-slate-200 text-slate-700 rounded-xl font-bold hover:bg-slate-300"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default App;